### DISCUSSION TITLE
How to properly set ENV's with helm?

### DISCUSSION THREAD

**Discussion by egorshoba** [blockscout/blockscout#10424] [Q&A]
Trying to deploy in my k8s cluster but can't set NEXT_PUBLIC_APP_HOST and NEXT_PUBLIC_API_HOST. Getting this error: 
Error: INSTALLATION FAILED: 1 error occurred:
	* Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal number into Go struct field EnvVar.spec.template.spec.containers.env.name of type string

Inline and values.yaml are giving the same result. 

helm install blockscout-explorer blockscout/blockscout-stack --set "blockscout.env[0].name=NEXT_PUBLIC_APP_HOST" --set "blockscout.env[0].value=ethereum-explorer.example.com"

**Comment by ghost** [comment]
We set variables via [`values.yaml`](https://helm.sh/docs/chart_template_guide/values_files/) file and it looks like this
```yaml
# Backend
blockscout:
  enabled: true
  env:
    MIX_ENV: prod

# Frontend
frontend:
  enabled: true
  env:
    NEXT_PUBLIC_APP_PROTOCOL: https
    NEXT_PUBLIC_APP_HOST: explorer.domain.tld
```

Not sure how to set properly variables via set command and would like to ask about
> `--set "blockscout.env[0].name=NEXT_PUBLIC_APP_HOST"`

Based on the documentation - Backend - [ENV Variables](https://docs.blockscout.com/for-developers/information-and-settings/env-variables) / Frontend - [Frontend Common ENVs](https://docs.blockscout.com/for-developers/information-and-settings/env-variables/frontend-common-envs), variable `NEXT_PUBLIC_APP_HOST` is related to the Frontend and should be set via `frontend.env` and not `blockscout.env`.
