### DISCUSSION TITLE
logs backend not showing

### DISCUSSION THREAD

**Discussion by budisetiawan760** [blockscout/blockscout#10723] [General]
i already add args like this, but the logs still created under root and thebackend cant write anything in there because permission, how i set it right way?

```
build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        RELEASE_VERSION: 6.8.0
        BLOCKSCOUT_UID: 1000
        BLOCKSCOUT_GID: 1000
        BLOCKSCOUT_USER: azureuser
        BLOCKSCOUT_GROUP: azureuser
        SHRINK_INTERNAL_TRANSACTIONS_ENABLED: true
```
