### DISCUSSION TITLE
http://localhost/stats error

### DISCUSSION THREAD

**Discussion by weimeme** [blockscout/blockscout#12068] [Q&A]
no data

error info:
```
proxy  | 192.168.65.1 - - [13/Mar/2025:09:23:55 +0000] "GET /api/v1/lines HTTP/1.1" 502 559 "[http://localhost/"](http://localhost/%22) "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36" "-"
proxy  | 192.168.65.1 - - [13/Mar/2025:09:23:56 +0000] "GET /api/v2/main-page/indexing-status HTTP/1.1" 200 133 "-" "OpenAPI-Generator/1.0.0/rust" "-"
proxy  | 192.168.65.1 - - [13/Mar/2025:09:23:57 +0000] "GET /api/v1/counters HTTP/1.1" 502 559 "[http://localhost/"](http://localhost/%22) "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36" "-"
proxy  | 2025/03/13 09:23:57 [error] 45#45: *395 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "GET /api/v1/counters HTTP/1.1", upstream: "[http://172.19.0.8:8050/api/v1/counters"](http://172.19.0.8:8050/api/v1/counters%22), host: "localhost:8080", referrer: "[http://localhost/"](http://localhost/%22)
proxy  | 2025/03/13 09:23:57 [error] 45#45: *395 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "GET /api/v1/lines HTTP/1.1", upstream: "[http://172.19.0.8:8050/api/v1/lines"](http://172.19.0.8:8050/api/v1/lines%22), host: "localhost:8080", referrer: "[http://localhost/"](http://localhost/%22)
proxy  | 192.168.65.1 - - [13/Mar/2025:09:23:57 +0000] "GET /api/v1/lines HTTP/1.1" 502 559 "[http://localhost/"](http://localhost/%22) "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36" "-"
```
<img width="1612" alt="image" src="https://github.com/user-attachments/assets/ccf23d78-9070-49ae-9734-0c49bbf0bcde" />

docker-compose.yml
```
version: '3.9'

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db
    networks:
      - bls

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init
    networks:
      - bls

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db
    networks:
      - bls

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        API_V1_READ_METHODS_DISABLED: "false"
        DISABLE_WEBAPP: "false"
        API_V1_WRITE_METHODS_DISABLED: "false"
        CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        ADMIN_PANEL_ENABLED: ""
        RELEASE_VERSION: 6.8.1
    links:
      - db:database
    environment:
        ETHEREUM_JSONRPC_HTTP_URL: https://scschain-rpc.novax.dev:2083/
        ETHEREUM_JSONRPC_TRACE_URL: https://scschain-rpc.novax.dev:2083/
        ETHEREUM_JSONRPC_WS_URL: wss://scschain-rpc.novax.dev:2083/
        CHAIN_ID: '1969'
    networks:
      - bls

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
    networks:
      - bls

  # sig-provider:
  #   extends:
  #     file: ./services/sig-provider.yml
  #     service: sig-provider

  # frontend:
  #   depends_on:
  #     - backend
  #   extends:
  #     file: ./services/frontend.yml
  #     service: frontend
  #   volumes:
  #     - ./services/.next/standalone/.next:/app/.next
  #     - ./services/.next/standalone/node_modules:/app/node_modules
  #     - ./services/.next/standalone/pages:/app/pages
  #     - ./services/.next/standalone/ui:/app/ui
  #     - ./services/.next/standalone/package.json:/app/package.json
  #     - ./services/.next/standalone/server.js:/app/server.js
  #     - ./services/.next/static:/app/.next/static
  #     - ./services/.next/public:/app/public

  frontend:
    depends_on:
      - backend
    extends:
      file: ../frontend/docker-compose.yml
      service: frontend
    restart: always
    env_file:
      -  ./envs/common-frontend.env
    volumes:
      - ./services/.next/standalone/.next:/app/.next
      - ./services/.next/standalone/node_modules:/app/node_modules
      - ./services/.next/standalone/pages:/app/pages
      - ./services/.next/standalone/ui:/app/ui
      - ./services/.next/standalone/package.json:/app/package.json
      - ./services/.next/standalone/server.js:/app/server.js
      - ./services/.next/static:/app/.next/static
      - ./services/.next/public:/app/public
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - bls

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init
    networks:
      - bls

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db
    networks:
      - bls

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats
    networks:
      - bls

  user-ops-indexer:
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer
    networks:
      - bls

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
    networks:
      - bls

networks:
  bls:
    driver: bridge

```

rpc:
```
http://scschain-rpc.novax.dev:2083
```

default.conf.template:
```
map $http_upgrade $connection_upgrade {

  default upgrade;
  ''      close;
}

server {
    listen       80;
    server_name  localhost;
    proxy_http_version 1.1;

    location ~ ^/(api(?!-docs$)|socket|sitemap.xml|auth/auth0|auth/auth0/callback|auth/logout) {
        proxy_pass            ${BACK_PROXY_PASS};
        proxy_http_version    1.1;
        proxy_set_header      Host "$host";
        proxy_set_header      X-Real-IP "$remote_addr";
        proxy_set_header      X-Forwarded-For "$proxy_add_x_forwarded_for";
        proxy_set_header      X-Forwarded-Proto "$scheme";
        proxy_set_header      Upgrade "$http_upgrade";
        proxy_set_header      Connection $connection_upgrade;
        proxy_cache_bypass    $http_upgrade;
    }
    location / {
        proxy_pass            ${FRONT_PROXY_PASS};
        proxy_http_version    1.1;
        proxy_set_header      Host "$host";
        proxy_set_header      X-Real-IP "$remote_addr";
        proxy_set_header      X-Forwarded-For "$proxy_add_x_forwarded_for";
        proxy_set_header      X-Forwarded-Proto "$scheme";
        proxy_set_header      Upgrade "$http_upgrade";
        proxy_set_header      Connection $connection_upgrade;
        proxy_cache_bypass    $http_upgrade;
    }
}
server {
    listen       8080;
    server_name  localhost;
    proxy_http_version 1.1;
    proxy_hide_header Access-Control-Allow-Origin;
    proxy_hide_header Access-Control-Allow-Methods;
    add_header 'Access-Control-Allow-Origin' 'http://localhost' always;
    add_header 'Access-Control-Allow-Credentials' 'true' always;
    add_header 'Access-Control-Allow-Methods' 'PUT, GET, POST, OPTIONS, DELETE, PATCH' always;

    location / {
        proxy_pass            http://stats:8050/;
        proxy_http_version    1.1;
        proxy_set_header      Host "$host";
        proxy_set_header      X-Real-IP "$remote_addr";
        proxy_set_header      X-Forwarded-For "$proxy_add_x_forwarded_for";
        proxy_set_header      X-Forwarded-Proto "$scheme";
        proxy_set_header      Upgrade "$http_upgrade";
        proxy_set_header      Connection $connection_upgrade;
        proxy_cache_bypass    $http_upgrade;
    }
}
server {
    listen       8081;
    server_name  localhost;
    proxy_http_version 1.1;
    proxy_hide_header Access-Control-Allow-Origin;
    proxy_hide_header Access-Control-Allow-Methods;
    add_header 'Access-Control-Allow-Origin' 'http://localhost' always;
    add_header 'Access-Control-Allow-Credentials' 'true' always;
    add_header 'Access-Control-Allow-Methods' 'PUT, GET, POST, OPTIONS, DELETE, PATCH' always;
    add_header 'Access-Control-Allow-Headers' 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,x-csrf-token' always;

    location / {
        proxy_pass            http://visualizer:8050/;
        proxy_http_version    1.1;
        proxy_buffering       off;
        proxy_set_header      Host "$host";
        proxy_set_header      X-Real-IP "$remote_addr";
        proxy_connect_timeout 30m;
        proxy_read_timeout    30m;
        proxy_send_timeout    30m;
        proxy_set_header      X-Forwarded-For "$proxy_add_x_forwarded_for";
        proxy_set_header      X-Forwarded-Proto "$scheme";
        proxy_set_header      Upgrade "$http_upgrade";
        proxy_set_header      Connection $connection_upgrade;
        proxy_cache_bypass    $http_upgrade;
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'http://localhost' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Allow-Methods' 'PUT, GET, POST, OPTIONS, DELETE, PATCH' always;
            add_header 'Access-Control-Allow-Headers' 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,x-csrf-token' always;
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
        }
    }
}
```

Everything else is using the default configuration. I'm not sure why the stats service is showing this error. If anyone has insights, I would appreciate your help. Thank you.
