### DISCUSSION TITLE
Refused to connect to API via proxy (Can't disable proxy)

### DISCUSSION THREAD

**Discussion by 0xDones** [blockscout/blockscout#8346] [Support] [answered]
I'm trying to run Blockscout Frontend on Kubernetes, but I'm not really being able to make it work. I'm running both the API and frontend behind nginx ingress controller, with TLS termination on the Load Balancer. API works fine, but I'm getting the following errors from the frontend.

![image](https://github.com/blockscout/blockscout/assets/29067941/b2c5a478-914f-4866-9c35-6ee128867d9f)

This is the env vars configuration for both services:

```yaml
# Frontend
env:
  NODE_ENV: production
  NEXT_PUBLIC_APP_HOST: blockscout.example.com
  NEXT_PUBLIC_APP_PROTOCOL: https
  NEXT_PUBLIC_USE_NEXT_JS_PROXY: "false"
  NEXT_PUBLIC_API_HOST: blockscout-api.example.com
  NEXT_PUBLIC_API_PROTOCOL: https
  NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: wss
  NEXT_PUBLIC_AD_TEXT_PROVIDER: none
  NEXT_PUBLIC_AD_BANNER_PROVIDER: none
 
# API
env:
  ETHEREUM_JSONRPC_VARIANT: geth
  ETHEREUM_JSONRPC_HTTP_URL: <omitted>
  ETHEREUM_JSONRPC_TRACE_URL: <omitted>
  # ETHEREUM_JSONRPC_WS_URL: <omitted>
  DATABASE_URL: postgresql://<omitted>
  SECRET_KEY_BASE: "<omitted>"
  API_V2_ENABLED: "true"
  ECTO_USE_SSL: "false"
  MIX_ENV: prod
  ETHEREUM_JSONRPC_HTTP_INSECURE: "true"
  NETWORK: POA
  INDEXER_DISABLE_ADDRESS_COIN_BALANCE_FETCHER: "true"
  ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES: "true"
  POOL_SIZE: "10"
```

I'm not sure if the request should be proxied with the env `NEXT_PUBLIC_USE_NEXT_JS_PROXY=false`.

It would be good to see any kind of log on the container as well.

I'm using this Helm Chart with some tweaks: https://github.com/blockscout/helm-charts/tree/main/charts/blockscout-stack

**Comment by nzenchik** [comment]
What is ingress configuration for both frontend and backend?

**Reply by 0xDones** [reply]
I'm using the following values for the Helm Chart:

```yaml
# Blockscout
    ingress:
      enabled: true
      className: "ingress-nginx"
      annotations: {}
      hostname: blockscout-api.<example.com>
      tls:
        enabled: false
      paths:
        - path: /
          pathType: Prefix
        - path: /api
          pathType: Prefix
        - path: /socket
          pathType: Prefix
        - path: /sitemap.xml
          pathType: Prefix
        - path: /auth/auth0
          pathType: Exact
        - path: /auth/auth0/callback
          pathType: Exact
        - path: /auth/logout
          pathType: Exact

# Blockscout Frontend
    ingress:
      enabled: true
      className: "ingress-nginx"
      annotations: {}
      hostname: blockscout.<example.com>
      tls:
        enabled: false
      paths:
        - path: /
```

Note:
When I first opened this discussion, I was using version 1.0.3 of the Helm Chart, which had a different path configuration, and now I updated it to 1.2.0.
