### DISCUSSION TITLE
Realtime Indexer is not working

### DISCUSSION THREAD

**Discussion by JoonsooWon** [blockscout/blockscout#8974] [General]
I was trying to use blockscout as explorer by using docker-compose for our private evm blockchain in AWS
But it's out of sync for the new block, what's the problem?
This is my backend env file

``` 
 backend:
    depends_on:
      - db
      - redis_db
    extends:
      file: ./services/docker-compose-backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        API_V1_READ_METHODS_DISABLED: "false"
        DISABLE_WEBAPP: "false"
        API_V1_WRITE_METHODS_DISABLED: "false"
        CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        ADMIN_PANEL_ENABLED: ""
        RELEASE_VERSION: 5.3.2
    links:
      - db:database
    environment:
        ETHEREUM_JSONRPC_HTTP_URL: https://${private-blockchain-domain}/rpc
        ETHEREUM_JSONRPC_TRACE_URL: https://${private-blockchain-domain}/rpc
        ETHEREUM_JSONRPC_WS_URL: wss://${private-blockchain-domain}/wc
        INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
        INDEXER_DISABLE_ADDRESS_COIN_BALANCE_FETCHER: 'true'
        INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'true'
        INDEXER_REALTIME_FETCHER_MAX_GAP: 1
        INDEXER_MEMORY_LIMIT : '3Gb'
        API_V2_ENABLED: 'true'
        CHAIN_ID: '${private-blockchain-id}'
```
