### DISCUSSION TITLE
Frontend account setup/configuration - 404

### DISCUSSION THREAD

**Discussion by lucgerrits** [blockscout/blockscout#9462] [Support]
Hi, I can't seem to make the account work on the new frontend/backend version, however it worked fine for blockscout 5.x before the frontend implementation.
When I click on the "sign-in" button of the frontend I get a 404.

Config for frontend:
  NEXT_PUBLIC_IS_ACCOUNT_SUPPORTED: "true"
  NEXT_PUBLIC_AUTH0_CLIENT_ID: "xxxxx"
  NEXT_PUBLIC_AUTH_URL: "https://frontend_url.com"
  NEXT_PUBLIC_LOGOUT_URL: "https://xxxx.us.auth0.com/v2/logout"

Config for backend:
  ACCOUNT_AUTH0_CALLBACK_URL: https://backend_url.com/auth/auth0/callback
  ACCOUNT_AUTH0_CLIENT_ID: xxx
  ACCOUNT_AUTH0_CLIENT_SECRET: xxx
  ACCOUNT_AUTH0_DOMAIN: xxx.us.auth0.com

Could somebody help please?

**Comment by lucgerrits** [comment]
The config file is like this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "block-explorer-v6.fullname" . }}-config
data:
  DATABASE_URL: "xxxx"
  ETHEREUM_JSONRPC_VARIANT: "geth"
  ETHEREUM_JSONRPC_HTTP_URL: "http://archives:9933"
  DATABASE_READ_ONLY_API_URL: "xxxx"
  ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES: 'false'
  SECRET_KEY_BASE: "xxx"
  MICROSERVICE_SC_VERIFIER_ENABLED: "true"
  MICROSERVICE_SC_VERIFIER_URL: "http://blockchain-dev-sc-verifier:8050/"
  ECTO_USE_SSL: 'false'
  BLOCKSCOUT_HOST: "my_domain.com"
  BLOCKSCOUT_PROTOCOL: https
  API_URL: https://my_domain.com
  PORT: '80'
  BLOCK_TRANSFORMER: base
  HEART_BEAT_TIMEOUT: '30'
  POOL_SIZE_API: '10'
  POOL_SIZE: '50'
  EMISSION_FORMAT: DEFAULT
  SUBNETWORK: "My Testnet"

  ACCOUNT_SENDGRID_API_KEY: ""
  ACCOUNT_SENDGRID_SENDER: ""

  DISABLE_INDEXER: 'false'
  DISABLE_REALTIME_INDEXER: 'false'
  DISABLE_CATCHUP_INDEXER: 'false'
  INDEXER_DISABLE_ADDRESS_COIN_BALANCE_FETCHER: 'false'
  INDEXER_DISABLE_TOKEN_INSTANCE_REALTIME_FETCHER: 'false'
  INDEXER_DISABLE_TOKEN_INSTANCE_RETRY_FETCHER: 'false'
  INDEXER_DISABLE_TOKEN_INSTANCE_SANITIZE_FETCHER: 'false'
  INDEXER_DISABLE_TOKEN_INSTANCE_LEGACY_SANITIZE_FETCHER: 'false'
  INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
  INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'true'

  ACCOUNT_AUTH0_CALLBACK_URL: https://my_domain.com/auth/auth0/callback
  ACCOUNT_AUTH0_CLIENT_ID: xxx
  ACCOUNT_AUTH0_CLIENT_SECRET: xxx
  ACCOUNT_AUTH0_DOMAIN: dev-xxx.us.auth0.com
  ACCOUNT_ENABLED: 'true'

  ACCOUNT_CLOAK_KEY: xxxx
  ACCOUNT_REDIS_URL: redis://:redis@blockchain-dev-redis:6379/

  APPS_MENU: 'true'
  EXTERNAL_APPS: "[]"
  COIN_NAME: ETH
  DISABLE_ADD_TO_MM_BUTTON: 'false'
  DISABLE_EXCHANGE_RATES: 'true'
  DISABLE_KNOWN_TOKENS: 'false'
  DISABLE_TOKEN_INSTANCE_FETCHER: 'false'
  DISPLAY_TOKEN_ICONS: 'false'
  EXCHANGE_RATES_FETCH_BTC_VALUE: 'false'
  FETCH_REWARDS_WAY: trace_block
  FOOTER_CHAT_LINK: '#'
  FOOTER_ENABLE_CHAT_LINK: 'false'
  FOOTER_ENABLE_FORUM_LINK: 'false'
  FOOTER_FORUM_LINK: '#'
  FOOTER_LINK_TO_OTHER_EXPLORERS: 'false'
  FOOTER_OTHER_EXPLORERS: '{}'
  SUPPORTED_CHAINS: '{}'

  SHOW_ADDRESS_MARKETCAP_PERCENTAGE: 'false'
  SHOW_MAINTENANCE_ALERT: 'false'
  MAINTENANCE_ALERT_MESSAGE: ''
  SHOW_PRICE_CHART: 'false'
  SHOW_PRICE_CHART_LEGEND: 'false'
  SHOW_TENDERLY_LINK: 'false'
  SHOW_TESTNET_LABEL: 'true'
  SHOW_TXS_CHART: 'true'

  DISABLE_WEBAPP: 'false'
  API_V2_ENABLED: 'true'
  API_V1_READ_METHODS_DISABLED: 'false'
  API_V1_WRITE_METHODS_DISABLED: 'false'
```
