### ISSUE TITLE
no matching manifest for linux/amd64 in the manifest list entries with Docker compose

### ISSUE THREAD

**Issue by ThaiKhim** [blockscout/blockscout#11231]
### Description

I built an Explorer panel using Docker however an error occurred:`no matching manifest for linux/amd64 in the manifest list entries`

A few days ago I tried a similar deployment and everything was fine until about 8 hours ago, all configurations in the .env files and the server's configuration kept from the first run.
![Screenshot from 2024-11-20 09-19-41](https://github.com/user-attachments/assets/881d1882-d4c7-4b1e-affa-699774035a6e)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Steps to reproduce

- Clone Src from Repo
- Set up .env
- run compose: `sudo docker compose up -d`

### Backend version

v6.9.1

### Elixir & Erlang/OTP versions

Elixir 1.17.3 (compiled with Erlang/OTP 27)

### Operating system

Linux

**Comment by ThaiKhim** [comment]
I found out that a few hours ago there was an update in the following image: [blockscout/blockscout-celo](https://hub.docker.com/r/blockscout/blockscout-celo)
does it have anything to do with this error?

**Comment by emrahsky** [comment]
yes I've been getting this error since yesterday

**Comment by ThaiKhim** [comment]
I think I found the reason: [pkgs/container/frontend](https://github.com/blockscout/frontend/pkgs/container/frontend/308266059?tag=latest)
![image](https://github.com/user-attachments/assets/390858a6-ef6c-428e-92ff-cf03005b5159)

The latest version of frontend does not have a version for amd64

**Comment by zsystm** [comment]
same here

**Comment by ThaiKhim** [comment]
I temporarily resolved it by returning it to v1.36.1 

in the frontend.yml file in service:

```
version: '3.9'

services:
  frontend:
    image: ghcr.io/blockscout/frontend:v1.36.1
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env

```
