### ISSUE TITLE
failed to fetch: :nxdomain.

### ISSUE THREAD

**Issue by ericlee42** [blockscout/blockscout#12677]
### Description

I have no idea why here has `failed to fetch: :nxdomain.` error.

I can connect to the geth node in the blockscout container.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

private chain

### Link to the page

localhost

### Steps to reproduce

env

```
DATABASE_URL=postgresql://blockscout:password@postgres:5432/blockscout
POOL_SIZE=50
POOL_SIZE_API=50
ECTO_USE_SSL=false

## node jsonrpc ##
ETHEREUM_JSONRPC_VARIANT=geth
ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:8545
ETHEREUM_JSONRPC_TRACE_URL=http://host.docker.internal:8545
ETHEREUM_JSONRPC_WS_URL=ws://host.docker.internal:8546
ETHEREUM_JSONRPC_GETH_TRACE_BY_BLOCK=true
ETHEREUM_JSONRPC_HTTP_INSECURE=true
ETHEREUM_JSONRPC_HTTP_TIMEOUT=120
ETHEREUM_JSONRPC_TRANSPORT=http
ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=false
EMISSION_FORMAT=DEFAULT
CHAIN_SPEC_PATH=http://host.docker.internal:8080/genesis.json

NETWORK=Ethereum
SUBNETWORK=Devnet
NETWORK_PATH=
BLOCKSCOUT_HOST=l1exp.devnet.metisdevops.link
BLOCKSCOUT_PROTOCOL=https
SECRET_KEY_BASE=O74D+KvMJqnqJ/t8BpO5VAzONl1/yL6zkBSiaxvxTFY=
DISABLE_WEBAPP=false
CHECK_ORIGIN=false
PORT=4000

## indexer ##
DISABLE_INDEXER=false
DISABLE_REALTIME_INDEXER=false
DISABLE_CATCHUP_INDEXER=false
INDEXER_TX_ACTIONS_ENABLE=true
ETHEREUM_JSONRPC_GETH_TRACE_BY_BLOCK=true
ETHEREUM_JSONRPC_DEBUG_TRACE_TRANSACTION_TIMEOUT=300s
INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE=1
INDEXER_INTERNAL_TRANSACTIONS_CONCURRENCY=3
INDEXER_DISABLE_CATALOGED_TOKEN_UPDATER_FETCHER=true
```
docker compose

```yaml
  blockscout:
    image: ghcr.io/blockscout/blockscout:8.1.1
    container_name: "blockscout"
    restart: unless-stopped
    stop_grace_period: 30s
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 4000:4000
    env_file:
      - ./backend.env
    volumes:
      - /data/blockscout/blockscout/:/app/logs/
    logging:
      driver: local
```

```yaml
  geth:
    image: "ethereum/client-go:v1.15.11"
    command:
      - --networkid=48815
      - --nodiscover
      - --miner.recommit=1s
      - --gcmode=archive
      - --http
      - --http.api=eth,net,web3,debug,txpool
      - --http.addr=0.0.0.0
      - --http.corsdomain=*
      - --http.vhosts=*
      - --ws
      - --ws.api=eth,net,web3,debug,txpool
      - --ws.addr=0.0.0.0
      - --ws.origins=*
    ports:
      - 8545:8545
      - 8546:8546
    volumes:
      - ./data/geth:/root/.ethereum
    logging:
      driver: "local"
```

### Backend version

8.1.1

### Frontend version

2.1.1

### Elixir & Erlang/OTP versions

docker

### Operating system

Linux

### Additional information

```
{"time":"2025-06-27T06:54:21.279Z","severity":"error","message":"failed to fetch: :nxdomain.  Block will be retried by catchup indexer.","metadata":{"step":"blocks","block_number":212,"fetcher":"block_realtime"}}
```

```
docker exec -it blockscout sh
/app $ 
/app $ printenv | grep ETHEREUM_JSONRPC_HTTP_URL
ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:8545
/app $ echo $ETHEREUM_JSONRPC_HTTP_URL
http://host.docker.internal:8545
/app $ 
/app $ 
/app $ 
/app $ 
/app $ curl http://host.docker.internal:8545 \
>   -X POST \
>   -H "Content-Type: application/json" \
>   --data '{"method":"eth_chainId","params":[],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"result":"0xbeaf"}
```
