### ISSUE TITLE
could not compile dependency :ex_keccak

### ISSUE THREAD

**Issue by enriavil1** [blockscout/blockscout#4349]
*Describe your issue here.*
I am trying to deploy block scout manually by following the steps in the documentation, but every time I run this command: 'mix do deps.get, local.rebar --force, deps.compile, compile' in the terminal I receive the following error:

Error: failed to run custom build command for `rustler v0.21.1`

Caused by:
  process didn't exit successfully: `/Users/enriavil1/Desktop/project/blockscout/_build/dev/rustler_crates/exkeccak/release/build/rustler-e08d5b548e9c5bcb/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Erlang version 2.16 not handled, please file a a bug report.', /Users/enriavil1/.cargo/registry/src/github.com-1ecc6299db9ec823/rustler-0.21.1/build.rs:50:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
could not compile dependency :ex_keccak, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_keccak", update it with "mix deps.update ex_keccak" or clean it with "mix deps.clean ex_keccak"
** (RuntimeError) Rust NIF compile error (rustc exit code 101)
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:68: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix 1.12.2) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.2) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.12.2) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
    (mix 1.12.2) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.12.2) lib/mix/tasks/compile.all.ex:36: Mix.Tasks.Compile.All.run/1

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Latests
* Operating System: MacOs
* Blockscout Version/branch: 3.7.0

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour
Expected to compile all mix dependencies

*Tell us what should happen.*
Expected to compile all mix dependencies

### Actual behaviour
compiles everything until the ex_keccak dependency

*Tell us what happens instead.*
compiles everything until the ex_keccak dependency

**Comment by nikitosing** [comment]
@enriavil1 You should install exactly the same versions as in [.tool-versions](https://github.com/blockscout/blockscout/blob/master/.tool-versions). The easiest way to do it is using [asdf](https://asdf-vm.com/#/core-manage-asdf)

**Comment by enriavil1** [comment]
I installed the tool versions by using asdf install in the directory, but it still gives me the same error

**Comment by nikitosing** [comment]
@enriavil1 Also you need to satisfy all this [requirements](https://docs.blockscout.com/for-developers/information-and-settings/requirements)

**Comment by enriavil1** [comment]
I am using a Mac so I installed all the ones it says on Mac with home-brew, but do I need to install the others too?

**Comment by enriavil1** [comment]
Maybe the asdf is not working properly. Every time I use asdf install it returns only "erlang <version> is already installed"

**Comment by enriavil1** [comment]
I figured out I had rustler installed with brew, so I deleted it, but now I receive a new error. :

Compiling NIF crate :exkeccak (native/exkeccak)...

Compiling on macOS requires special link args in order to compile
correctly.

Rustler is currently working around this issue in the compiler task.
This will be removed in v1.0.0 in favor of a user supplied .cargo/config
file.

To remove this warning, please create /Users/enriavil1/Desktop/project/blockscout/deps/ex_keccak/native/exkeccak/.cargo/config
with the following content:

      [target.x86_64-apple-darwin]
      rustflags = [
          "-C", "link-arg=-undefined",
          "-C", "link-arg=dynamic_lookup",
      ]

See https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/MachOTopics/1-Articles/executing_files.html
for more details.


could not compile dependency :ex_keccak, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_keccak", update it with "mix deps.update ex_keccak" or clean it with "mix deps.clean ex_keccak"
** (ErlangError) Erlang error: :enoent
    (elixir 1.12.2) lib/system.ex:1041: System.cmd("cargo", ["rustc", "--release", "--", "-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"], [cd: "/Users/enriavil1/Desktop/project/blockscout/deps/ex_keccak/native/exkeccak", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/Users/enriavil1/Desktop/project/blockscout/_build/dev/rustler_crates/exkeccak"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:59: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix 1.12.2) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.2) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.12.2) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
    (mix 1.12.2) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2

**Comment by enriavil1** [comment]
> I figured out I had rustler installed with brew, so I deleted it, but now I receive a new error. :
> 
> Compiling NIF crate :exkeccak (native/exkeccak)...
> 
> Compiling on macOS requires special link args in order to compile
> correctly.
> 
> Rustler is currently working around this issue in the compiler task.
> This will be removed in v1.0.0 in favor of a user supplied .cargo/config
> file.
> 
> To remove this warning, please create /Users/enriavil1/Desktop/project/blockscout/deps/ex_keccak/native/exkeccak/.cargo/config
> with the following content:
> 
> ```
>   [target.x86_64-apple-darwin]
>   rustflags = [
>       "-C", "link-arg=-undefined",
>       "-C", "link-arg=dynamic_lookup",
>   ]
> ```
> 
> See https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/MachOTopics/1-Articles/executing_files.html
> for more details.
> 
> could not compile dependency :ex_keccak, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_keccak", update it with "mix deps.update ex_keccak" or clean it with "mix deps.clean ex_keccak"
> ** (ErlangError) Erlang error: :enoent
> (elixir 1.12.2) lib/system.ex:1041: System.cmd("cargo", ["rustc", "--release", "--", "-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"], [cd: "/Users/enriavil1/Desktop/project/blockscout/deps/ex_keccak/native/exkeccak", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/Users/enriavil1/Desktop/project/blockscout/_build/dev/rustler_crates/exkeccak"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
> (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:59: Mix.Tasks.Compile.Rustler.compile_crate/1
> (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
> (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
> (mix 1.12.2) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
> (mix 1.12.2) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
> (mix 1.12.2) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
> (mix 1.12.2) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2

 the thing is that the directory specified doesn't exist

**Comment by nikitosing** [comment]
Did you install Rust?

**Comment by enriavil1** [comment]
Yeah I was trying to solve the issue and installed Rust, but I just deleted it again to see if it would change, since they both gave me different errors

**Comment by AleksMVP** [comment]
@enriavil1 Hi! You need to install erlang opt23 and elixir 1.11*.  And don't forget to export necessary variables after install rust. Also, you might use my docker container https://hub.docker.com/r/aleksn7/blockscout or the whole docker-compose file. 

After rust install:
```
export PATH="$HOME/.cargo/bin:$PATH" 
```

Erlang and elixir install example for ubuntu:
```
wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
sudo dpkg -i erlang-solutions_2.0_all.deb
sudo apt-get update
sudo apt-get install -y erlang=1:23*

wget https://github.com/elixir-lang/elixir/releases/download/v1.11.0/Precompiled.zip
sudo unzip Precompiled.zip -d /opt/elixir
export PATH="$PATH:/opt/elixir/bin"
```

Docker-compose file example:
```
version: '3'
services: 
  blockscout:
    image: aleksn7/blockscout:v1.1
    container_name: blockscout
    ports:
      - 4000:4000
    environment: 
      - ETHEREUM_JSONRPC_HTTP_URL=http://geth:8545
      - ETHEREUM_JSONRPC_WS_URL=ws://geth:8546
      - ETHEREUM_JSONRPC_TRACE_URL=http://geth:8545 
      - ETHEREUM_JSONRPC_VARIANT=geth
      - COIN=ETH
      - DATABASE_URL=postgresql://postgres:123@postgres:5432/blockscout?ssl=false
    links: 
      - postgres
      - geth
      - blockscout-migrations
    command: mix phx.server
    restart: always

  blockscout-migrations:
    image: aleksn7/blockscout:v1.1
    container_name: blockscout-migrations
    environment: 
      - DATABASE_URL=postgresql://postgres:123@postgres:5432/blockscout?ssl=false
    links:
      - postgres
      - geth
    command: mix do ecto.create, ecto.migrate

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=blockscout
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
```
