### ISSUE TITLE
Blockchain explorer showing nothing on a private net

### ISSUE THREAD

**Issue by coulterminer** [blockscout/blockscout#5424]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): no idea
* Operating System: Windows 10
* Blockscout Version/branch: Latest

### Steps to reproduce (showing only postgres and blockscout I can show the entire script if needed)

  postgres:
    image: postgres:12
    command: postgres -c 'max_connections=500'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  blockscout:
    image: ulamlabs/blockscout:latest
    links:
      - geth
      - postgres
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:@postgres:5432/postgres?ssl=false
      - ETHEREUM_JSONRPC_VARIANT=geth
      - ETHEREUM_JSONRPC_HTTP_URL=http://geth:8545
      - ETHEREUM_JSONRPC_WS_URL=ws://geth:8546
      - MIX_ENV=prod
      - BLOCKSCOUT_HOST=localhost
      - COIN=eth
      - NETWORK=POA
      - SUBNETWORK=Kutoro

### Expected behaviour

Blockscout should be able to see transactions and show them. Blocks and everything

### Actual behaviour

It doesnt update nor show anything

![image](https://user-images.githubusercontent.com/20375102/162085114-8d71eca3-090a-41df-9f55-29eb2bc790d4.png)

current block
![image](https://user-images.githubusercontent.com/20375102/162085290-36bc5d96-1af6-471c-b2c6-b373b1e20400.png)

**Comment by vbaranov** [comment]
@coulterminer 
> image: ulamlabs/blockscout:latest

You should use `blockscout/blockscout:latest`

Also, set `ETHEREUM_JSONRPC_TRACE_URL=http://geth:8545/`

**Comment by coulterminer** [comment]
> @coulterminer did it help what I previously suggested?

I was just about to get back to you on that. Nothing has changed! am I doing something wrong, heres my current code. No blocks or balances are still being shown. 

```
  postgres:
    image: postgres:12
    command: postgres -c 'max_connections=500'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  blockscout:
    image: ulamlabs/blockscout:latest
    links:
      - geth
      - postgres
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:@postgres:5432/postgres?ssl=false
      - ETHEREUM_JSONRPC_VARIANT=geth
      - ETHEREUM_JSONRPC_HTTP_URL=http://geth:8545
      - ETHEREUM_JSONRPC_WS_URL=ws://geth:8545
      - MIX_ENV=prod
      - BLOCKSCOUT_HOST=localhost
      - COIN=Kutoro
      - NETWORK=POA
      - SUBNETWORK=Kutoro
```

Am I doing something wrong, I am running on the port with geth...
