### ISSUE TITLE
internal_transaction fetcher garbaged debug_traceTransaction call (leads to "tracer not found" output)

### ISSUE THREAD

**Issue by ongrid** [blockscout/blockscout#5729]
internal_transaction fetcher composes garbaged JSON RPC `debug_traceTransaction` request. Its value of `tracer` field gets populated with the garbage code:

Here is the network dump
```
T 172.25.0.3:41496 -> 172.17.0.1:9650 [AP] #1456
POST /ext/bc/2J5AZfDNqWtg9FAXGZkP4qVRUp3SD9XcQrYZz878BmZ7ybpCN5/rpc HTTP/1.1.
Host: 172.17.0.1:9650.
User-Agent: hackney/1.18.1.
Content-Type: application/json.
Content-Length: 247635.
.
[{"id":0,"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0x02db41436b1ecb99e771f8b763b344867257e5af399ee28a03b563592a470fab",
{"timeout":"5s","tracer":"// tracer allows Geth's `debug_traceTransaction` to mimic the output of Parity's `trace_replayTransaction`\n{\n    
// The call stack of the EVM execution.\n    callStack: [{}],\n\n    
// step is invoked for every opcode that the VM executes.\n    step(log, db) {\n        
// Capture any errors immediately\n        const error = log.getError();\n\n        if (error !== undefined) {\n            this.fault(log, db);\n        } else {\n            this.success(log, db);\n        }\n    },\n\n   
 // fault is invoked when the actual execution of an opcode fails.\n    fault(log, db) {\n        
// If the topmost call already reverted, don't handle the additional fault again\n        if (this.topCall().error === undefined) {\n            this.putError(log);\n        }\n    },\n\n    putError(log) {\n        if (this.callStack.length > 1) {\n            this.putErrorInTopCall(log);\n        } else {\n            this.putErrorInBottomCall(log);\n        }\n    },\n\n    putErrorInTopCall(log) {\n        // Pop off the just failed call\n        const call = this.callStack.pop();\n        this.putErrorInCall(log, call);\n        this.pushChildCall(call);\n    },\n\n    putErrorInBottomCall(log) {\n        const call = this.bottomCall();\n        this.putErrorInCall(log, call);\n    },\n\n    putErrorInCall(log, call) {\n        call.error = log.getError();\n\n        // Consume all available gas and clean any leftovers\n        if (call.gasBigInt !== undefined) {\n            call.gasUsedBigInt = call.gasBigInt;\n        }\n\n        delete call.outputOffset;\n        delete call.outputLength;\n    },\n\n    topCall() {\n        return this.callStack[this.callStack.length - 1];\n    },\n\n    bottomCall() {\n        return this.callStack[0];\n    },\n\n    pushChildCall(childCall) {\n        const topCall = this.topCall();\n\n        if (topCall.calls === undefined) {\n            topCall.calls = [];\n        }\n\n        topCall.calls.push(childCall);\n    },\n\n    pushGasToTopCall(log) {\n        const topCall = this.topCall();\n\n        if (topCall.gasBigInt === undefined) {\n            topCall.gasBigInt = log.getGas();\n        }\n        topCall.gasUsedBigInt = topCall.gasBigInt - log.getGas() - log.getCost();\n    },\n\n    success(log, db) {\n        const op = log.op.toString();\n\n        this.beforeOp(log, db);\n\n        switch (op) {\n            case 'CREATE':\n                this.createOp(log);\n                break;\n            case 'CREATE2':\n                this.create2Op(log);\n                break;\n            case 'SELFDESTRUCT':\n                this.selfDestructOp(log, db);\n                break;\n            case 'CALL':\n            case 'CALLCODE':\n            case 'DELEGATECALL':\n            case 'STATICCALL':\n
```

The node responds with

```
##
T 172.17.0.1:9650 -> 172.25.0.3:47944 [AP] #1506
HTTP/1.1 200 OK.
Content-Type: application/json.
Node-Id: NodeID-GJmP6MiBfHjGFsbwvt2EvZUWCcpkzzEUP.
Vary: Accept-Encoding.
Vary: Origin.
Date: Wed, 06 Jul 2022 08:25:53 GMT.
Content-Length: 1098.
.
[{"jsonrpc":"2.0","id":0,"error":{"code":-32000,"message":"tracer not found"}},{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"tracer not found"}},{"jsonrpc":"2.0","id":2,"error":{"code":-32000,"message":"tracer not found"}},{"jsonrpc":"2.0","id":3,"error":{"code":-32000,"message":"tracer not found"}},{"jsonrpc":"2.0","id":4,"error":{"code":-32000,"message":"tracer not found"}},{"jsonrpc":"2.0","id":5,"error":{"code":-32000,"message":"tracer not found"}},{"jsonrpc":"2.0","id":6,"error":{"code":-32000,"message":"tracer not found"}},{"jsonrpc":"2.0","id":7,"error":{"code":-32000,"message":"tracer not found"}},{"jsonrpc":"2.0","id":8,"error":{"code":-32000,"message":"tracer not found"}},{"jsonrpc":"2.0","id":9,"error":{"code":-32000,"message":"tracer not found"}},{"jsonrpc":"2.0","id":10,"error":{"code":-32000,"message":"tracer not found"}},{"jsonrpc":"2.0","id":11,"error":{"code":-32000,"message":"tracer not found"}},{"jsonrpc":"2.0","id":12,"error":{"code":-32000,"message":"tracer not found"}},{"jsonrpc":"2.0","id":13,"error":{"code":-32000,"message":"tracer not found"}}]
```

Blockscout's output:

```
2022-07-06T08:15:54.009 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{code: -32000, data: %{block_number: 163568, transaction_hash: "0x0c2c2889e322062dd84863cb6750eefd5358e7074e74e75c39a2d950d281122f", transaction_index: 8}, message: "tracer not found"}, %{code: -32000, data: %{block_number: 163568, transaction_hash: "0x12e883eed4d32fb24bd2e5859740c993bbb1d7ae4d6aeb4209280a24d748df22", transaction_index: 1}, message: "tracer not found"}, %{code: -32000, data: %{block_number: 163568, transaction_hash: "0x1457c324d073bcf1a283f030a253fec216d6a4a7fec1ee2f08f1a520beb93dae", transaction_index: 3}, message: "tracer not found"}, %{code: -32000, data: %{block_number: 163568, transaction_hash: "0x26aa39aa6b725b3dee922d4b58bf13378eb595cb043f3d79959c258d01581d8a", transaction_index: 0}, message: "tracer not found"}, %{code: -32000, data: %{block_number: 163568, transaction_hash: "0x324a90ec5bf4c999a8c481a71d635efb9a331a35c8bedea58484f9a844be4193", transaction_index: 6}, message: "tracer not found"}, %{code: -32000, data: %{block_number: 163568, transaction_hash: "0x7daaba2c601d256fc770fa824d23905b5e347a55eb27f3afc501c2e18e715f6a", transaction_index: 2}, message: "tracer not found"}, %{code: -32000, data: %{block_number: 163568, transaction_hash: "0xb47229a0ef6cea71892436d1e18e537ffbf94a20629493988a9ecdfe48ebe873", transaction_index: 7}, message: "tracer not found"}, %{code: -32000, data: %{block_number: 163568, transaction_hash: "0xbb7ed8ff52b95bcd01f9fb37e607ea807dfcd8aebb6af3ce07db0b10f421cf12", transaction_index: 5}, message: "tracer not found"}, %{code: -32000, data: %{block_number: 163568, transaction_hash: "0xfb8dfd68bf8f95f22a378d9a5ea21df1f6644c79aa2df98c318e3b8dd9d184b9", transaction_index: 4}, message: "tracer not found"}]
```

### Environment

tried latest master https://github.com/blockscout/blockscout/commit/4e5ac69d89f5556d7e62840cab1be8af8e4c5e3a and 1-week old commit https://github.com/blockscout/blockscout/commit/62211b7a3a51de0a54e957d93bba71ecf6dfea59 using local docker-compose build.

docker-compose.blockscout.yml file:
```
  blockscout:
    depends_on:
      - db
#    image: blockscout/blockscout:latest
    build:
      context: blockscout
      dockerfile: docker/Dockerfile
    restart: always
    command: "mix do ecto.create, ecto.migrate, phx.server"
    env_file:
      - ./common-blockscout.env
    environment:
      ETHEREUM_JSONRPC_HTTP_URL: http://172.17.0.1:9650/ext/bc/2J5AZfDNqWtg9FAXGZkP4qVRUp3SD9XcQrYZz878BmZ7ybpCN5/rpc
      ETHEREUM_JSONRPC_TRACE_URL: http://172.17.0.1:9650/ext/bc/2J5AZfDNqWtg9FAXGZkP4qVRUp3SD9XcQrYZz878BmZ7ybpCN5/rpc
      ETHEREUM_JSONRPC_WS_URL: ws://172.17.0.1:9650/ext/bc/2J5AZfDNqWtg9FAXGZkP4qVRUp3SD9XcQrYZz878BmZ7ybpCN5/rpc
      EXTERNAL_APPS: "[{\"title\": \"Faucet\", \"url\": \"https://faucet.devz.website/\"}]"
      SUBNETWORK: "FitFi Subnet"
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/blockscout"
      HIDE_BLOCK_MINER: 'true'
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'false'
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'false'
      INDEXER_DISABLE_ADDRESS_COIN_BALANCE_FETCHER: 'false'
      FIRST_BLOCK: 163000
      TRACE_FIRST_BLOCK: 163000
```

Had the same issue with official docker image pulled from dockerhub. Similar issue #1536

Node: [avalanchego](https://github.com/ava-labs/avalanchego) (go-ethereum flavour of RPC)

### Steps to reproduce

```
git clone https://github.com/blockscout/blockscout.git
docker-compose -f docker-compose.blockscout.yml build
docker-compose -f docker-compose.blockscout.yml up -d
```
