### ISSUE TITLE
Chain indexing slows down and never finishes

### ISSUE THREAD

**Issue by ongrid** [blockscout/blockscout#5777]
Chain indexing never finishes. UI displays alert on top of the page with `Indexing Tokens - We're indexing this chain right now. Some of the counts may be inaccurate.` or `XX% Blocks Indexed - We're indexing this chain right now. Some of the counts may be inaccurate.`.

Some observations:
* The issue doesn't seem to be related to compute resources - same happens on both DigitalOcean middle-size droplets and top AWS EC2 instances (48 vCPU, 384 GB RAM, NVME SSD)
* Slowdown seem to happen after about ~1 hour of intensive work. For the first hour or two loadavg is steadily between `10.0-20.0` then it goes down to `1.0-3.0`. 

### Environment

* Chain:

It's a private avalanche [subnet](https://github.com/step-app-fi/step-node) with geth-flavored API.
Node is co-located on same machine and available via internal docker interface. Node is synced and confirmed to be healthy. Chain has 419000 blocks to the moment and grows at speed of 10 seconds per block. Blocks have gasLimit of 8M gas and filled by 80%-100%.

* Elixir & Erlang/OTP versions (`elixir -version`):

Built from official [Dockerfile](https://github.com/blockscout/blockscout/blob/7f39e41cab5bce137b2ff6c7f746f55c027d1216/docker/Dockerfile#L1)
```
Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:48:48] [ds:48:48:10] [async-threads:1] [jit:no-native-stack]
Elixir 1.13.1 (compiled with Erlang/OTP 24)
```

* Operating System:

```
AWS official image
Canonical, Ubuntu, 22.04 LTS, amd64 jammy image build on 2022-06-09
```

* Machine:

High-end AWS EC-2 VM [i3en.12xlarge](https://aws.amazon.com/ru/ec2/instance-types/i3en/): 48 vCPU, 384 GB RAM, 4 x 7500 NVMe SSD, 50 Gbps network,  9.5 Gbps EBS storage bandwidth

* Blockscout Version/branch: 

```
commit 7f39e41cab5bce137b2ff6c7f746f55c027d1216 (origin/master, origin/HEAD)
Merge: 99820f7dc e7b97dc33
Author: Victor Baranov <baranov.viktor.27@gmail.com>
Date:   Wed Jul 20 14:23:55 2022 +0300

    Merge pull request #5761 from blockscout/dependabot/npm_and_yarn/apps/block_scout_web/assets/moment-2.29.4
    
    Bump moment from 2.29.2 to 2.29.4 in /apps/block_scout_web/assets
```

https://github.com/blockscout/blockscout/commit/7f39e41cab5bce137b2ff6c7f746f55c027d1216  

* Blockscout configuration:

```
  blockscout:
    depends_on:
      - db
    image: blockscout:latest
    build: 
      context: blockscout
      dockerfile: docker/Dockerfile
      args:
        COIN: 'FITFI'
        COIN_NAME: 'FITFI' 
        NETWORK_PATH: '/'
        CHAIN_ID: '0x3039'
        JSON_RPC: https://rpc.staging
        SUBNETWORK: "Testnet"
    restart: always
    command: "mix do ecto.create, ecto.migrate, phx.server"
    env_file:
      - ./common-blockscout.env
    environment:
      COIN: 'FITFI'
      COIN_NAME: 'FITFI'
      ETHEREUM_JSONRPC_HTTP_URL: http://172.17.0.1:9650/ext/bc/2J5AZfDNqWtg9FAXGZkP4qVRUp3SD9XcQrYZz878BmZ7ybpCN5/rpc
      ETHEREUM_JSONRPC_TRACE_URL: http://172.17.0.1:9650/ext/bc/2J5AZfDNqWtg9FAXGZkP4qVRUp3SD9XcQrYZz878BmZ7ybpCN5/rpc
      ETHEREUM_JSONRPC_WS_URL: ws://172.17.0.1:9650/ext/bc/2J5AZfDNqWtg9FAXGZkP4qVRUp3SD9XcQrYZz878BmZ7ybpCN5/rpc
      EXTERNAL_APPS: "[{\"title\": \"Faucet\", \"url\": \"https://faucet.step.network/\"}]"
      SUBNETWORK: "Step Testnet"
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/blockscout"
      HIDE_BLOCK_MINER: 'true'
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'true'
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'false'
      INDEXER_DISABLE_ADDRESS_COIN_BALANCE_FETCHER: 'false'
      NETWORK_PATH: '/'
      CHAIN_ID: '0x3039'
      JSON_RPC: 'https://rpc.staging.step.network/'
```

Note: INTERNAL_TRANSACTIONS_FETCHER disabled due to https://github.com/blockscout/blockscout/issues/5729 

### Steps to reproduce

Ready to bring up at my environment and provide remote access to it.

### Expected behaviour

* Expected to see the banner with increasing percentage of indexed %.
* While indexing it's expected to see high load and higher resource consumption (loadavg, memory, processes, CPU usage).
* More hardware resources should lead to faster indexing. Bottleneck should be
* When 100% achieved, indexing banner should disappear. Load expected to decrease.

### Actual behaviour

* Indexing threads seem to degrade over time and never finish.
