### ISSUE TITLE
disconnected: ** (DBConnection.ConnectionError) client

### ISSUE THREAD

**Issue by DRIgnazGortngschirl** [blockscout/blockscout#6405]
Getting DB Connection issues when using the config as below, am I doing something wrong /  config wrong ?

### Environment

* Deployment type (Docker-compose): 
```
  redis_db:
    image: 'redis:alpine'
    command: redis-server
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: '10'
    restart: unless-stopped

  db:
    networks:
      - back-tier
    image: postgres:14
    restart: always
    command: postgres -c 'max_connections=2000'
    volumes:
      - '/mnt/tank/blockscout/db-index:/var/lib/postgresql/data'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
     - 5432:5432
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: '10'
    restart: unless-stopped

  blockscout:
    depends_on:
      - db
      - smart-contract-verifier
      - redis_db
    build:
      context: ../blockscout
      dockerfile: ../blockscout/docker/Dockerfile
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: '10'
    restart: unless-stopped
    links:
      - db
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
#    extra_hosts:
#      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../blockscout/docker-compose/envs/common-blockscout.env
    networks:
      - web
      - back-tier
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.explorerblockscout.entrypoints=websecure"
      - "traefik.http.routers.explorerblockscout.rule=Host(`explorer-blockscout.etc-network.info`)"
      - "traefik.http.routers.explorerblockscout.tls=true"
      - "traefik.http.services.explorerblockscout.loadbalancer.server.port=4000"

```
* Elixir & Erlang/OTP versions (`elixir -version`): -
* Node JS version (`node -v`): -
* Operating System: Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
* Blockscout Version/branch/commit: latest (local image build)
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): -

### Steps to reproduce

use the above provided docker-compose settings and  .env config

https://txt.mariomichel.com/?551ad7fcdc1b07a3=#SsybmDDDgEAgTDhtauLXfTHNsQqdd3VpPVQtkpdYD7C

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

```
etc-blockscout-1  | 2022-11-07T09:42:17.819 application=explorer [info] tx/per day chart: save records
etc-blockscout-1  | 2022-11-07T09:42:18.131 application=explorer [info] tx/per day chart: number of inserted 10
etc-blockscout-1  | 2022-11-07T09:42:23.540 application=phoenix [info] Running BlockScoutWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:4000 (http)
etc-blockscout-1  | 2022-11-07T09:42:23.604 application=phoenix [info] Access BlockScoutWeb.Endpoint at ://:4000
etc-blockscout-1  | 2022-11-07T09:42:26.525 application=db_connection [info] Postgrex.Protocol (#PID<0.4124.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.5249.0> exited
etc-blockscout-1  | 2022-11-07T09:42:26.526 application=db_connection [info] Postgrex.Protocol (#PID<0.4134.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.5228.0> exited
etc-blockscout-1  | 2022-11-07T09:42:26.528 application=db_connection [info] Postgrex.Protocol (#PID<0.4211.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.5213.0> exited
etc-blockscout-1  | 2022-11-07T09:42:26.528 application=db_connection [info] Postgrex.Protocol (#PID<0.4106.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.5189.0> exited
etc-blockscout-1  | 2022-11-07T09:42:28.684 application=db_connection [info] Postgrex.Protocol (#PID<0.4418.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.5297.0> exited
etc-blockscout-1  | 2022-11-07T09:42:29.578 application=db_connection [info] Postgrex.Protocol (#PID<0.4107.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.5405.0> exited
etc-blockscout-1  | 2022-11-07T09:42:29.580 [notice] Application indexer exited: shutdown
```

*Tell us what happens instead.*
