### ISSUE TITLE
Smart Contract Verification

### ISSUE THREAD

**Issue by l0gun0v** [blockscout/blockscout#6824]
<img width="908" alt="Screenshot 2023-02-06 at 00 32 44" src="https://user-images.githubusercontent.com/98526047/216852253-11cf1639-2bc9-44cb-8dbd-d2633665cc69.png">

Hi, I build blockscout from docker-compose-no-build-ganache. And have this problem when I try to verify my contract in web page. Can you help me ? And also I will write code to automatic verification of contract, is it possible ?
(If you can send me guide plz)

Thanks you. 

my docker-compose:
```

version: '3.8'

services:
  #redis_db:
  #  image: 'redis:alpine'
  #  ports:
  #    - 6379:6379
  #  container_name: redis_db
  #  command: redis-server
  #  volumes:
  #    - ./redis-data:/data

  db:
    image: postgres:14
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7432:5432

  blockscout:
   # platform: linux/x86_64
    depends_on:
      - db
      - smart-contract-verifier
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    pull_policy: always
    restart: always
    container_name: 'blockscout'
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'ganache'
        ETHEREUM_JSONRPC_HTTP_URL: https://*************/
        #ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8545/
        #INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'true'
        #INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
        DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
        ECTO_USE_SSL: 'false'
        SECRET_KEY_BASE: '56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN'
        CHAIN_ID: '1337'
    ports:
      - 4000:4000
    volumes:
      - ./logs/:/app/logs/

  smart-contract-verifier:
    platform: linux/x86_64
    image: ghcr.io/blockscout/smart-contract-verifier:${SMART_CONTRACT_VERIFIER_DOCKER_TAG:-latest}
    pull_policy: always
    restart: always
    container_name: 'smart-contract-verifier'
    env_file:
      -  ./envs/common-smart-contract-verifier.env
    ports:
      - 8043:8043

  #visualizer:
  #  platform: linux/x86_64
  #  image: ghcr.io/blockscout/visualizer:${VISUALIZER_DOCKER_TAG:-latest}
  #  pull_policy: always
  #  restart: always
  #  container_name: 'visualizer'
  #  env_file:
  #    -  ./envs/common-visualizer.env
  #  ports:
  #    - 8050:8050

  #sig-provider:
  #  platform: linux/x86_64
  #  image: ghcr.io/blockscout/sig-provider:${SIG_PROVIDER_DOCKER_TAG:-main}
  #  pull_policy: always
  #  restart: always
  #  container_name: 'sig-provider'
  #  ports:
  #    - 8051:8050
```
