### ISSUE TITLE
ERROR! Config provider Config.Reader failed

### ISSUE THREAD

**Issue by ranjith-edx** [blockscout/blockscout#7549]
I'm getting this error while running the image using docker compose 

Crash dump is being written to: erl_crash.dump...done
ERROR! Config provider Config.Reader failed with:
** (Code.LoadError) could not load /app/releases/5.1.4/config_helper.exs. Reason: enoent
    (elixir 1.14.0) lib/code.ex:1807: Code.find_file!/2
    (elixir 1.14.0) lib/code.ex:1184: Code.eval_file/2
    /app/releases/5.1.4/runtime.exs:5: (file)
    (elixir 1.14.0) src/elixir.erl:298: anonymous fn/4 in :elixir.eval_external_handler/1
    (stdlib 4.0.1) erl_eval.erl:748: :erl_eval.do_apply/7
    (stdlib 4.0.1) erl_eval.erl:136: :erl_eval.exprs/6
    (elixir 1.14.0) src/elixir.erl:288: :elixir.eval_forms/3
    (elixir 1.14.0) lib/module/parallel_checker.ex:100: Module.ParallelChecker.verify/1

{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.Code.LoadError',file=><<"/app/releases/5.1.4/config_helper.exs">>,message=><<"could not load /app/releases/5.1.4/config_helper.exs. Reason: enoent">>,reason=>enoent},[{'Elixir.Code','find_file!',2,[{file,"lib/code.ex"},{line,1807}]},{'Elixir.Code',eval_file,2,[{file,"lib/code.ex"},{line,1184}]},{elixir_eval,'__FILE__',1,[{file,"/app/releases/5.1.4/runtime.exs"},{line,5}]},{elixir,'-eval_external_handler/1-fun-2-',4,[{file,"src/elixir.erl"},{line,298}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,748}]},{erl_eval,exprs,6,[{file,"erl_eval.erl"},{line,136}]},{elixir,eval_forms,3,[{file,"src/elixir.erl"},{line,288}]},{'Elixir.Module.ParallelChecker',verify,1,[{file,"lib/module/parallel_checker.ex"},{line,100}]}]}}
init terminating in do_boot ({,[{Elixir.Code,find_file!,2,[{_},{_}]},{Elixir.Code,eval_file,2,[{_},{_}]},{elixir_eval,__FILE__,1,[{_},{_}]},{elixir,-eval_external_handler/1-fun-2-,4,[{_},{_}]},{erl_eval,do_apply,7,[{_},{_}]},{erl_eval,exprs,6,[{_},{_}]},{elixir,eval_forms,3,[{_},{_}]},{Elixir.Module.ParallelChecker,verify,1,[{_},{_}]}]})

### Environment

* Deployment type : Docker-compose
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`): 16
* Operating System: ubuntu
* Blockscout Version/branch/commit: [v5.1.4-beta](https://github.com/blockscout/blockscout/releases/tag/v5.1.4-beta)
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Ganache

### Steps to reproduce

i just downloaded the zip from release and build the image and tried to run it with docker compose and the error pops in the docker logs 

is there any solution to this i checked on previous issues similar type of config.reader issue but it  did'nt gave me solution issue id of that one is [#6378](https://github.com/blockscout/blockscout/issues/6378#issue-1431225606)

**Comment by ranjith-edx** [comment]
i went inside the docker compose folder in cli and entered this command 

docker-compose -f docker-compose-no-build-ganache.yml up -d 

after running it i got error in the log @vbaranov

**Comment by vbaranov** [comment]
I cannot reproduce with:
```
git clone https://github.com/blockscout/blockscout
git checkout v5.1.4-beta
docker-compose -f docker-compose-no-build-ganache.yml up -d
```

If even this doesn't work you can try with 5.1.5, which is the latest release or try to remove stale images from the machine.

**Comment by ranjith-edx** [comment]
will clear all the images and test with 5.1.5 and update  here

**Comment by ranjith-edx** [comment]
Hi @vbaranov  i got the same error on 5.1.5 and the master branch as well  

while trying to build custom image 

![image](https://github.com/blockscout/blockscout/assets/115977226/82928c54-fc3a-4833-bfab-78110deffdc0)

steps to reproduce 

cloned the master branch or v5.1.5

command used for building the docker image from the main folder ( i have used local/blockscout:latest  name to identify the image created from the local )

**docker build -t local/blockscout:latest . -f docker/Dockerfile**

once the image got built 

went to docker-compose-no-build-ganache.yml file and just renamed the image name 

![image](https://github.com/blockscout/blockscout/assets/115977226/7f76a9f9-cb4c-44a6-afe3-ce1e739e7f92)

and then from docker compose folder 

**docker-compose -f docker-compose-no-build-ganache.yml up -d**

and while checking the log with 

**docker logs blockscout -f**

i got the above error 

please create a readme file with steps how to create custom image i'have not made any changes in other files except docker-compose file for changing the image name please look on this issue not able to build custom image

**Comment by ranjith-edx** [comment]
Hi @vbaranov  have you tried it let me know if your facing the same issue bcz i'm not able to build custom image in the latest versions ..... i mean like the image is getting built but after getting built it gives config.reader error after running it

**Comment by Chomtana** [comment]
Add RELEASE_VERSION and BLOCKSCOUT_VERSION args to the Dockerfile build

RELEASE_VERSION=5.1.5
BLOCKSCOUT_VERSION=5.1.5

For docker compose, it will be like this:

```yaml
  blockscout:
    depends_on:
      - db
      - smart-contract-verifier
      - redis_db
    build:
      context: ..
      args:
        RELEASE_VERSION: 5.1.5
        BLOCKSCOUT_VERSION: 5.1.5
    restart: always
    stop_grace_period: 5m
    container_name: 'blockscout'
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8545/
        DATABASE_URL: postgresql://postgres:@db:5432/blockscout?ssl=false
        ECTO_USE_SSL: 'false'
        SECRET_KEY_BASE: '56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN'
    ports:
      - 4000:4000
    volumes:
      - ./logs/:/app/logs/
```

And then

```
docker compose down -v
docker compose up --force-recreate --build
```
