### ISSUE TITLE
Awaiting internal transactions for reason - Ganache node forking Ethereum mainnet

### ISSUE THREAD

**Issue by AlissonRS** [blockscout/blockscout#7857]
Any failed transactions will show "Awaiting internal transactions for reason". The node is a Ganache forking Ethereum mainnet.

Example of a failed tx hash on a public hosted explorer: https://explorer-flokifi.forkfy.io/tx/0x7ef2fd6cdc70d8822b125a2a82fcb2d416cd9a4d50c26f56ce7127e952e58f08

The Ganache node is publicly available here: https://flokifi-rpc.forkfy.io

It also doesn't show internal transactions (not sure if this is expected because of Ganache).

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker image: **blockscout/blockscout:latest**
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Ganache (forking eth mainnet)

Environment variables as per below:

```
      env:
        - name: ACCOUNT_ENABLED
          value: "false"
        - name: ACCOUNT_POOL_SIZE
          value: "5"
        - name: API_RATE_LIMIT
          value: "50"
        - name: API_RATE_LIMIT_BY_IP
          value: "3000"
        - name: API_RATE_LIMIT_BY_IP_TIME_INTERVAL
          value: 5m
        - name: API_RATE_LIMIT_BY_KEY
          value: "50"
        - name: API_RATE_LIMIT_BY_WHITELISTED_IP
          value: "50"
        - name: API_RATE_LIMIT_TIME_INTERVAL
          value: 1s
        - name: API_RATE_LIMIT_UI_V2_TOKEN_TTL_IN_SECONDS
          value: "18000"
        - name: API_RATE_LIMIT_UI_V2_WITH_TOKEN
          value: "5"
        - name: BLOCK_TRANSFORMER
          value: base
        - name: CACHE_ADDRESS_SUM_PERIOD
          value: "3600"
        - name: CACHE_ADDRESS_TOKENS_USD_SUM_PERIOD
          value: "3600"
        - name: CACHE_ADDRESS_TOKEN_TRANSFERS_COUNTER_PERIOD
          value: "1800"
        - name: CACHE_ADDRESS_TRANSACTIONS_COUNTER_PERIOD
          value: "1800"
        - name: CACHE_ADDRESS_TRANSACTIONS_GAS_USAGE_COUNTER_PERIOD
          value: "1800"
        - name: CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL
          value: "1800"
        - name: CACHE_AVERAGE_BLOCK_PERIOD
          value: "1800"
        - name: CACHE_BLOCK_COUNT_PERIOD
          value: "7200"
        - name: CACHE_MARKET_HISTORY_PERIOD
          value: "21600"
        - name: CACHE_TOKEN_HOLDERS_COUNTER_PERIOD
          value: "3600"
        - name: CACHE_TOKEN_TRANSFERS_COUNTER_PERIOD
          value: "3600"
        - name: CACHE_TOTAL_GAS_USAGE_PERIOD
          value: "3600"
        - name: CACHE_TXS_COUNT_PERIOD
          value: "7200"
        - name: CHAIN_ID
          value: "31337"
        - name: CHECKSUM_ADDRESS_HASHES
          value: "true"
        - name: CHECKSUM_FUNCTION
          value: eth
        - name: COIN_BALANCE_HISTORY_DAYS
          value: "90"
        - name: CONTRACT_MAX_STRING_LENGTH_WITHOUT_TRIMMING
          value: "2040"
        - name: CONTRACT_VERIFICATION_ALLOWED_EVM_VERSIONS
          value: homestead,tangerineWhistle,spuriousDragon,byzantium,constantinople,petersburg,istanbul,berlin,london,paris,default
        - name: DECODE_NOT_A_CONTRACT_CALLS
          value: "true"
        - name: DISABLE_EXCHANGE_RATES
          value: "true"
        - name: DISABLE_INDEXER
          value: "false"
        - name: DISABLE_READ_API
          value: "false"
        - name: DISABLE_REALTIME_INDEXER
          value: "false"
        - name: DISABLE_TOKEN_INSTANCE_FETCHER
          value: "true"
        - name: DISABLE_WEBAPP
          value: "false"
        - name: DISABLE_WRITE_API
          value: "false"
        - name: DISPLAY_TOKEN_ICONS
          value: "false"
        - name: ECTO_USE_SSL
          value: "false"
        - name: EIP_1559_ELASTICITY_MULTIPLIER
          value: "2"
        - name: EMISSION_FORMAT
          value: DEFAULT
        - name: ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES
          value: "false"
        - name: ETHEREUM_JSONRPC_TRANSPORT
          value: http
        - name: ETHEREUM_JSONRPC_VARIANT
          value: ganache
        - name: FETCH_REWARDS_WAY
          value: trace_block
        - name: FIRST_BLOCK
          value: "17618091"
        - name: HEART_BEAT_TIMEOUT
          value: "30"
        - name: HIDE_BLOCK_MINER
          value: "false"
        - name: INDEXER_DISABLE_EMPTY_BLOCKS_SANITIZER
          value: "false"
        - name: INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER
          value: "false"
        - name: INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER
          value: "false"
        - name: INDEXER_HIDE_INDEXING_PROGRESS_ALERT
          value: "true"
        - name: INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE
          value: "10"
        - name: ETHEREUM_JSONRPC_DEBUG_TRACE_TRANSACTION_TIMEOUT
          value: "60"
        - name: ETHEREUM_JSONRPC_HTTP_INSECURE
          value: "true"
        - name: ETHEREUM_JSONRPC_HTTP_TIMEOUT
          value: "60"
        - name: MAX_SIZE_UNLESS_HIDE_ARRAY
          value: "50"
        - name: MICROSERVICE_ETH_BYTECODE_DB_INTERVAL_BETWEEN_LOOKUPS
          value: 10m
        - name: MICROSERVICE_SC_VERIFIER_ENABLED
          value: "true"
        - name: MICROSERVICE_SC_VERIFIER_TYPE
          value: sc_verifier
        - name: MICROSERVICE_SC_VERIFIER_URL
          value: http://smart-contract-verifier:8150/
        - name: MICROSERVICE_SIG_PROVIDER_ENABLED
          value: "true"
        - name: MICROSERVICE_SIG_PROVIDER_URL
          value: http://sig-provider:8151/
        - name: MICROSERVICE_VISUALIZE_SOL2UML_ENABLED
          value: "true"
        - name: MICROSERVICE_VISUALIZE_SOL2UML_URL
          value: http://visualizer:8152/
        - name: NETWORK_PATH
          value: /
        - name: POOL_SIZE
          value: "90"
        - name: POOL_SIZE_API
          value: "10"
        - name: PORT
          value: "4000"
        - name: SHOW_ADDRESS_MARKETCAP_PERCENTAGE
          value: "true"
        - name: SHOW_MAINTENANCE_ALERT
          value: "false"
        - name: SHOW_PRICE_CHART
          value: "false"
        - name: SHOW_TENDERLY_LINK
          value: "false"
        - name: SHOW_TXS_CHART
          value: "true"
        - name: SOURCIFY_INTEGRATION_ENABLED
          value: "false"
        - name: TOKEN_METADATA_UPDATE_INTERVAL
          value: "172800"
        - name: TRACE_FIRST_BLOCK
          value: "17618091"
        - name: TXS_HISTORIAN_INIT_LAG
          value: "0"
        - name: TXS_STATS_DAYS_TO_COMPILE_AT_INIT
          value: "10"
        - name: TXS_STATS_ENABLED
          value: "true"
        - name: UNCLES_IN_AVERAGE_BLOCK_TIME
          value: "false"
```

### Steps to reproduce

Send a transaction that will fail (e.g. transfer some ERC20 token without enough balance) on this RPC: https://flokifi-rpc.forkfy.io

Check the failed transaction hash on the explorer hosted here: https://explorer-flokifi.forkfy.io

### Expected behaviour

It should be able to show the error message.

### Actual behaviour

It's showing  "Awaiting internal transactions for a reason" in the explorer.

Thanks for your help in advance!!!
