### ISSUE TITLE
ERROR 53100 (disk_full) could not resize shared memory segment "/PostgreSQL.1022215856" to 196736 bytes: No space left on device

### ISSUE THREAD

**Issue by yzh-d** [blockscout/blockscout#8648]
### Description

I'm getting this error

2023-10-18T01:16:51.577 [error] GenServer Explorer.Chain.Cache.NewContractsCounter terminating
** (Postgrex.Error) ERROR 53100 (disk_full) could not resize shared memory segment "/PostgreSQL.1022215856" to 196736 bytes: No space left on device
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:945: Ecto.Adapters.SQL.execute/6
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:159: Ecto.Repo.Queryable.one!/3
    (explorer 5.2.3) lib/explorer/chain/cache/new_contracts_counter.ex:74: Explorer.Chain.Cache.NewContractsCounter.consolidate/0
    (explorer 5.2.3) lib/explorer/chain/cache/new_contracts_counter.ex:44: Explorer.Chain.Cache.NewContractsCounter.handle_continue/2
    (stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4
Last message: {:continue, :ok}
State: %{consolidate?: true}

But the instance has doesn't seems to be running out of space
![image](https://github.com/blockscout/blockscout/assets/30540477/c83e2b89-1bfd-411b-aa4d-6e855f16a263)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ganache

### Type of the chain

L1

### Backend version

master

### Frontend version

Self-developed front-end

### Elixir & Erlang/OTP versions

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Linux

### Additional information

This error should be the reason why there is no data in Daily transactions on October 17th

<img width="1350" alt="image" src="https://github.com/blockscout/blockscout/assets/30540477/d9965c67-2757-4ed2-abbf-0bbd25aba3b8">

**Comment by yzh-d** [comment]
After restarting, Daily transactions have data from October 17th again.
The error message for disk_full is temporarily gone.

<img width="1337" alt="image" src="https://github.com/blockscout/blockscout/assets/30540477/9bd68d20-072e-456f-81d7-854c9adaaefd">

**Comment by vbaranov** [comment]
@yzh-d which volume do you use for Postgres. Apparently, Postgres Docker container experiences luck of space.

**Comment by yzh-d** [comment]
I haven't encountered this problem for the time being, and I'm not sure which operation I did to solve the problem.

**Comment by aostrun** [comment]
I stumbled upon a similar issue, and I managed to fix it by increasing the size of the shared memory of the docker container running Blockscout & stats databases. Both databases are PostgreSQL databases which have issues with restricted size of shared memory. ([source](https://www.instaclustr.com/blog/postgresql-docker-and-shared-memory/))

To fix the issue, specify the `shm_size` on the PostgreSQL database containers:
```yaml
db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    image: postgres:14
    user: 2000:2000
    shm_size: 256m  # <-- Add this line
    restart: always
    container_name: 'db'
    command: postgres -c 'max_connections=200' -c 'client_connection_check_interval=60000'
    environment:
        POSTGRES_DB: 'blockscout'
        POSTGRES_USER: 'blockscout'
        POSTGRES_PASSWORD: 'ceWb1MeLBEeOIfk65gU8EjF8'
    ports:
      - 7432:5432
    volumes:
      - ./blockscout-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blockscout -d blockscout"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
```

```yaml
stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    image: postgres:14
    user: 2000:2000
    shm_size: 256m  # <-- Add this line
    restart: always
    container_name: 'stats-postgres'
    command: postgres -c 'max_connections=200'
    environment:
        POSTGRES_DB: 'stats'
        POSTGRES_USER: 'stats'
        POSTGRES_PASSWORD: 'n0uejXPl61ci6ldCuE2gQU5Y'
    ports:
      - 7433:5432
    volumes:
      - ./stats-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats -d stats"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
```
